import Schedule from '@/components/tigers/schedule';
import { ArrowUpRight, ArrowRight, Play, Ticket } from 'lucide-react';
const stadium='https://tigers.co.kr/files/resource/2020/03/10/20200310132332.8b3-67afebfcfa41.jpg';
const official='https://tigers.co.kr';
const videos=[{id:'epOyXZGjfuI',tag:'챔필덕관',title:'끝내기의 순간, 챔필이 뜨거워졌다.',desc:'10회말 만루, 변우혁이 해결한 짜릿한 승부',url:official+'/contents/tv/1041583'},{id:'Py8J5h7Y3h4',tag:'승리의 순간',title:'오늘도 끝내기. 함께 만든 승리.',desc:'그라운드에서 전하는 선수들의 생생한 목소리',url:official+'/contents/tv/1041582'}];
export default function Home(){return <>
<main id="main-content"><section className="hero" aria-labelledby="hero-title"><img className="hero-image" src={stadium} alt="관중으로 가득 찬 광주-기아 챔피언스 필드" fetchPriority="high"/><div className="hero-shade"/><div className="hero-top"><span><i/> GWANGJU. OUR HOME.</span><span>PASSION NEVER STOPS — EST. 1982</span></div><div className="hero-content"><p className="eyebrow">ONE TEAM. ONE ROAR.</p><h1 id="hero-title">ALWAYS<br/><span>ROARING.</span></h1><div className="hero-bottom"><div><p className="hero-korean">우리의 함성은, 멈추지 않는다.</p><p className="hero-desc">뜨거운 열정으로 하나 되는 순간. 우리는 타이거즈입니다.</p><a className="button light" href="/schedule"><Ticket size={16}/> 경기일정 · 예매 플랜 <ArrowUpRight size={18}/></a></div><a className="hero-scroll" href="#story">SCROLL TO EXPLORE <span>↓</span></a></div></div><div className="hero-counter"><b>HOME</b><span/><span className="counter-caption">THE HOME OF TIGERS</span></div></section>
<div className="red-strip"><span>WE ARE TIGERS</span><b>✦</b><span>함께, 더 뜨겁게</span><b>✦</b><span>GWANGJU PRIDE</span><b>✦</b><span>WE ARE TIGERS</span><b>✦</b></div>
<Schedule compact/><section className="intro section" id="story"><div><p className="eyebrow red">THE TIGERS SPIRIT</p><h2>야구 그 이상의,<br/>우리라는 자부심.</h2></div><div className="intro-right"><p>첫 투구의 설렘부터 마지막 아웃의 함성까지.<br/>그라운드 위의 선수와 관중석의 우리가 함께 만드는 이야기.<br/>타이거즈의 모든 순간에 당신이 있습니다.</p><a className="text-link" href={official+'/history'} target="_blank" rel="noreferrer">타이거즈의 역사 <ArrowUpRight size={19}/></a></div><div className="est"><small>OUR STORY BEGAN IN</small><strong>1982<span>↗</span></strong></div></section>
<section className="tv section" id="tv"><div className="section-title"><div><p className="eyebrow red">BEYOND THE GAME</p><h2>TIGERS <span>TV</span><span className="red tiny-dot">●</span></h2></div><a className="text-link" href={official+'/contents/tv'} target="_blank" rel="noreferrer">모든 영상 <ArrowUpRight size={18}/></a></div><div className="videos">{videos.map((v,i)=><article className="video-card" key={v.id}><a className="video-image" href={'https://www.youtube.com/watch?v='+v.id} target="_blank" rel="noreferrer" aria-label={v.title+' 유튜브에서 재생'}><img src={'https://i.ytimg.com/vi/'+v.id+'/maxresdefault.jpg'} alt={v.title} loading="lazy"/><span className="video-tag">{v.tag}</span><span className="play"><Play size={25} fill="currentColor"/></span><span className="video-index">0{i+1} / TIGERS TV</span></a><div className="video-caption"><div><p className="video-date">2026.09.04 <span>•</span> {v.tag}</p><h3><a href={v.url} target="_blank" rel="noreferrer">{v.title}</a></h3><p>{v.desc}</p></div><ArrowUpRight size={25}/></div></article>)}</div></section>
<section className="field home-field"><div className="field-image"><img src={stadium} alt="광주-기아 챔피언스 필드" loading="lazy"/></div><div className="field-content"><p className="eyebrow">THIS IS OUR HOME</p><h2>CHAMPIONS<br/><span>FIELD.</span></h2><p className="field-korean">첫 직관도, 늘 오던 길처럼.</p><p>좌석과 편의시설, 챔필로 오는 길을 한곳에서 확인하세요.</p><a className="button light" href="/stadium">경기장 둘러보기 <ArrowUpRight size={18}/></a></div></section>
<section className="closing section"><p className="eyebrow red">WITH TIGERS. WITH YOU.</p><h2>다음 함성의 주인공은, <span>당신.</span></h2><a href="/schedule">내가 함께할 경기 선택하기 <ArrowRight size={22}/></a></section></main>
</>}