'use client';
import {useEffect,useState} from 'react';
import {Download,MapPin} from 'lucide-react';
import {type Game,stateLabel,calendarFile,validMonth} from '@/lib/game-model';
import {TicketEstimate,useGuide} from './schedule';
const prettyDate=(date:string)=>new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short',timeZone:'Asia/Seoul'}).format(new Date(date+'T12:00:00+09:00'));
export default function GameDetail({id}:{id:string}){
 const [game,setGame]=useState<Game|null>(null);const [error,setError]=useState('');const [meta,setMeta]=useState<{stale:boolean;message?:string}|null>(null);const [retry,setRetry]=useState(0);const [back,setBack]=useState('/schedule');const guide=useGuide();
 useEffect(()=>{const q=new URLSearchParams(location.search);const value=q.get('from');if(value?.startsWith('/schedule?'))setBack(value)},[]);
 useEffect(()=>{const month=id.slice(0,4)+'-'+id.slice(4,6);if(!/^[A-Za-z0-9]{9,40}$/.test(id)||!validMonth(month)){setError('올바르지 않은 경기 주소입니다.');return;}const c=new AbortController();setError('');setGame(null);fetch('/api/schedule?month='+month,{signal:c.signal}).then(async r=>{const d=await r.json() as {games:Game[];stale:boolean;message?:string;error?:string};if(!r.ok)throw Error(d.error||'경기를 불러오지 못했습니다.');const found=d.games.find((g:Game)=>g.id===id);if(!found)throw Error('이 경기를 찾을 수 없습니다. 경기일정에서 다시 선택해 주세요.');setGame(found);setMeta(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[id,retry]);
 function download(game:Game){const blob=new Blob([calendarFile(game)],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=game.id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

 return <main id="main-content" className="destination-page"><nav className="breadcrumbs" aria-label="현재 위치"><a href="/">홈</a><span>/</span><a href={back}>경기일정</a><span>/</span><span>경기 상세</span></nav><div className="detail-page game-page"><a className="back-link" href={back}>← 경기일정으로</a>{error?<div role="alert" className="records-empty"><h1>경기 정보 확인</h1><p>{error}</p><button className="outline-button" onClick={()=>setRetry(n=>n+1)}>다시 시도</button></div>:!game?<div className="records-empty" role="status">경기 정보를 불러오는 중입니다.</div>:<><h1 className="dialog-title">{game.away} <span>vs</span> {game.home}</h1><p className="dialog-subtitle">{prettyDate(game.date)} {game.time} · {game.stadium} · {game.isHome?'홈경기':'원정경기'}</p><div className="game-detail-score"><span>{game.away}</span><strong>{['live','finished'].includes(game.state)?`${game.awayScore??'—'} : ${game.homeScore??'—'}`:'VS'}</strong><span>{game.home}</span><small>{stateLabel[game.state]}{game.result?' · '+game.result:''}{meta?.stale?' · 저장본':''}</small></div><div className="detail-actions">{game.state==='scheduled'&&/^\d{2}:\d{2}$/.test(game.time)&&<button onClick={()=>download(game)}><Download size={16}/> 내 캘린더에 저장</button>}<a href="/stadium"><MapPin size={16}/> 챔피언스 필드 안내</a></div>{game.isHome&&['scheduled','live'].includes(game.state)?<TicketEstimate key={game.id} game={game} guide={guide} stale={meta?.stale}/>:<div className="notice">{!game.isHome?'원정 경기입니다. 이 사이트의 좌석 요금과 구장 안내는 광주 홈경기를 기준으로 합니다.':'종료·취소·서스펜디드 경기는 새 예매 플랜을 제공하지 않습니다.'}</div>}</>}</div></main>
}
