'use client';
import {useState} from 'react';
import {useUrlState} from './url-state';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect} from '@/components/ui/native-select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {MapPin,ArrowRight,Maximize2,Plus,Minus,Bus,TrainFront,Car,Copy,Accessibility,Baby,Utensils,Clock,Ticket,Info} from 'lucide-react';
import {seatOptions,POLICY_URL} from '@/lib/game-model';
import {useGuide} from './schedule';
const stadium='https://tigers.co.kr/files/resource/2020/03/10/20200310132332.8b3-67afebfcfa41.jpg';
const routes={terminal:{name:'유스퀘어 · 광주종합버스터미널',bus:'매월16',stop:'광주기아챔피언스필드 정문 정류장',walk:'하차 후 정문까지 도보 약 3분',alternative:'매월26·일곡38·송암47·상무64 → 제2광천교 하차 → 도보 약 6분'},station:{name:'광주송정역 · KTX / SRT',bus:'송정98',stop:'무등야구장 정류장',walk:'하차 후 정문까지 도보 약 5분',alternative:'지하철 1호선 농성역에서 택시로 이동할 수도 있습니다.'},airport:{name:'광주공항',bus:'일곡38 · 공항역 정류장',stop:'제2광천교 정류장',walk:'하차 후 정문까지 도보 약 6분',alternative:'택시 이용 시 목적지를 광주-기아 챔피언스 필드로 지정하세요.'}};
const won=(n:number)=>n.toLocaleString('ko-KR')+'원';
export default function Stadium(){const guide=useGuide();const [seatId,setSeatId]=useState('cheer');const [query,setQuery]=useUrlState({tab:'seats'},(_k,v)=>['seats','tickets','facilities','transport'].includes(v));const tab=query.tab;const setTab=(tab:string)=>setQuery({tab});const [zoom,setZoom]=useState(1);const [mapOpen,setMapOpen]=useState(false);const [origin,setOrigin]=useState<keyof typeof routes>('terminal');const [copied,setCopied]=useState('');const seat=seatOptions.find(s=>s.id===seatId)!;const route=routes[origin];const map=guide?.fieldUrl||'https://tigers.co.kr/files/resource/2026/03/260330_fieldGuide.png';
 async function copyAddress(){try{await navigator.clipboard.writeText('광주-기아 챔피언스 필드, 북구 서림로 10');setCopied('주소를 복사했습니다.')}catch{setCopied('북구 서림로 10 · 주소를 직접 복사해 주세요.')}}
 return <section id="field" className="stadium-guide"><div className="field"><div className="field-image"><img src={stadium} alt="광주-기아 챔피언스 필드의 그라운드와 관중석" loading="lazy"/><span><MapPin size={16}/> GWANGJU, KOREA</span></div><div className="field-content"><p className="eyebrow">THIS IS OUR HOME</p><h2>CHAMPIONS<br/><span>FIELD.</span></h2><p className="field-korean">첫 직관도, 늘 오던 길처럼.</p><p>나에게 맞는 좌석부터 입장 게이트, 편의시설까지.<br/>경기장에 도착하기 전, 여기서 준비하세요.</p><div className="stadium-stats"><div><strong>20,500</strong><span>관람석</span></div><div><strong>99 / 121<span>m</span></strong><span>좌우 / 중앙 펜스</span></div><div><strong>5<span>층</span></strong><span>지상 규모</span></div></div></div></div>
 <div className="section stadium-body"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="stadium-tabs" aria-label="챔피언스 필드 안내"><TabsTrigger value="seats">좌석 둘러보기</TabsTrigger><TabsTrigger value="tickets">입장권 · 예매 안내</TabsTrigger><TabsTrigger value="facilities">시설 · 관람 가이드</TabsTrigger><TabsTrigger value="transport">오시는 길</TabsTrigger></TabsList>
 <TabsContent value="seats"><div className="guide-heading"><div><p className="eyebrow red">FIND YOUR SEAT</p><h3>어디에서 함께할까요?</h3><p>좌석을 선택해 위치와 관람 특징을 비교해 보세요.</p></div><button className="outline-button" onClick={()=>{setZoom(1);setMapOpen(true)}}><Maximize2 size={17}/> 안내도 크게 보기</button></div><div className="seat-layout"><div className="stadium-map"><img src={map} alt="2026 광주-기아 챔피언스 필드 공식 좌석 및 편의시설 안내도" loading="lazy"/><div><span>3루 · 홈 응원 구역</span><span>1루 · 원정 측</span></div><p className="muted small">블록·게이트의 정확한 위치는 안내도를 확대해 확인하세요.</p></div><div className="seat-explorer"><div className="seat-buttons" aria-label="좌석 종류 선택">{seatOptions.map(s=><button key={s.id} aria-pressed={seatId===s.id} onClick={()=>setSeatId(s.id)}>{s.name}</button>)}</div><div className="seat-selection"><span className="eyebrow red">YOUR VIEW</span><h4>{seat.name}</h4><p>{seat.note}</p><p className="seat-location"><MapPin size={16}/>{seat.area}</p><div className="seat-prices"><div><span>주중 · 월–목</span><b>{won(seat.weekday)}</b></div><div><span>주말 · 금–일 / 공휴일</span><b>{won(seat.weekend)}</b></div></div><p className="small muted">일반 성인 1인 기준 · 2026.08.18 게시 요금{seat.group>1?` · ${seat.group}매 단위 구매`:''}</p>{guide&&!guide.policyCurrent&&<p className="notice">최신 정책 확인이 필요합니다. 위 금액은 8월 18일 안내 기준입니다.</p>}<a className="action-button" href="/schedule">경기를 선택하고 예상 금액 보기 <ArrowRight size={18}/></a></div></div></div></TabsContent>
 <TabsContent value="tickets"><div className="guide-heading"><div><p className="eyebrow red">PLAN YOUR GAME DAY</p><h3>예매 전에, 한눈에.</h3><p>2026 시즌 공식 입장권 안내를 바탕으로 정리했습니다.</p></div><a className="outline-button" href="/schedule"><Ticket size={17}/> 경기 선택하기</a></div>{guide&&!guide.policyCurrent&&<p className="notice">공식 안내가 변경되었거나 연결이 지연되었습니다. 아래는 2026년 8월 18일 게시 정책을 정리한 내용입니다.</p>}<div className="ticket-facts"><article><span>01 / OPEN</span><Clock/><h4>경기 7일 전, 오전 11시</h4><p>일반 예매 시작. 온라인 예매는 경기 시작 후 1시간 30분까지 가능합니다.</p></article><article><span>02 / ENTRY</span><Ticket/><h4>입장은 경기 2시간 전부터</h4><p>현장 판매는 경기 시작 2시간 전부터 7회 초까지. 운영 상황에 따라 바뀔 수 있습니다.</p></article><article><span>03 / CHECK</span><Info/><h4>1인 최대 8매</h4><p>테이블석은 분할 구매가 불가합니다. 4인 테이블은 4매를 함께 구매하세요.</p></article></div><div className="price-policy-grid"><div><h4 className="block-heading">좌석별 일반 성인 요금</h4><div className="price-table"><Table><TableHeader><TableRow><TableHead>좌석</TableHead><TableHead>주중</TableHead><TableHead>주말·공휴일</TableHead></TableRow></TableHeader><TableBody>{seatOptions.map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{won(s.weekday)}</TableCell><TableCell>{won(s.weekend)}</TableCell></TableRow>)}</TableBody></Table></div><p className="small muted">1인 기준. 주중 월–목 / 주말 금–일·공휴일. 특별석 일부와 할인 요금은 공식 원문을 참고하세요.</p></div><div className="policy-list"><h4 className="block-heading">예매 · 취소 체크리스트</h4><details open><summary>예매 방법과 수수료</summary><p>PC는 티켓링크, 모바일은 KIA타이거즈 앱 또는 티켓링크 앱에서 예매할 수 있습니다. 인터넷·모바일·전화 예매 수수료는 1,000원이며 현장 판매는 무료입니다.</p></details><details><summary>예매 취소는 언제까지?</summary><p>경기 시작 4시간 전까지 예매처에서 취소할 수 있습니다. 예매 당일 취소는 예매 수수료 환불 및 취소 수수료가 무료입니다. 이후에는 예매 수수료가 환불되지 않고 입장권 금액의 10% 취소 수수료가 발생합니다.</p></details><details><summary>우천으로 경기가 취소되면?</summary><p>기상 악화로 경기 취소 또는 정식 경기로 인정되지 않은 경우 결제 내역이 전액 환불됩니다. 5회 이후 정식 경기 인정 및 서스펜디드 경기에는 예외가 있으니 해당 예매처 안내를 확인하세요.</p></details><details><summary>할인과 어린이 관람</summary><p>일반석은 만 18세 이하 청소년·의무복무 군인 30%, 만 12세 이하 어린이 등 대상자 50% 할인 안내가 있습니다. 할인 중복은 불가하며 증빙 확인이 필요합니다. 36개월 이하 유아는 보호자 동반 시 좌석 없이 무료 입장할 수 있습니다.</p></details><details><summary>경기일이나 좌석을 바꾸고 싶어요</summary><p>구매한 표의 경기일과 좌석은 직접 변경할 수 없습니다. 해당 예매처에서 기존 예매를 취소하고 다시 예매해야 합니다. 취소 시점별 수수료를 먼저 확인하세요.</p></details></div></div><a className="source-link" href={guide?.policyUrl||POLICY_URL} target="_blank" rel="noreferrer">출처: 구단 입장권 안내 전체 보기</a></TabsContent>
 <TabsContent value="facilities"><div className="guide-heading"><div><p className="eyebrow red">FEEL AT HOME</p><h3>경기만큼 편안한 하루.</h3><p>아이와 함께, 친구와 함께. 필요한 시설을 미리 찾아보세요.</p></div><button className="outline-button" onClick={()=>{setZoom(1);setMapOpen(true)}}><Maximize2 size={17}/> 시설 위치 확인</button></div><div className="facility-cards"><article><Baby/><h4>아이와 함께</h4><p>수유실은 3층 112·118 블록 뒤편, 놀이방은 3층 113·116 블록 뒤편에 있습니다.</p><span>외야에는 키즈챔피언스필드와 샌드파크가 표시되어 있습니다.</span></article><article><Accessibility/><h4>이동과 접근성</h4><p>휠체어석은 내야 관람 구역에 분산되어 있습니다. 안내도에서 휠체어석 표시와 가까운 게이트를 함께 확인하세요.</p><span>필요한 현장 지원은 종합안내소에 문의하세요.</span></article><article><Utensils/><h4>먹거리와 편의시설</h4><p>3층 1·3루와 5층에는 식음료 매장이, 구장 곳곳에는 물품보관함과 현금인출기가 안내되어 있습니다.</p><span>매장 위치·운영은 공식 안내도와 당일 현장 안내를 기준으로 확인하세요.</span></article></div><div className="arrival-plan"><div><p className="eyebrow red">BEFORE FIRST PITCH</p><h4>첫 직관, 이렇게 준비하세요.</h4></div><ol><li><b>출발 전</b><span>경기 시간·우천 공지와 티켓 권종을 확인하고 할인 증빙을 준비하세요.</span></li><li><b>구장 도착</b><span>표의 블록 번호로 가까운 게이트를 찾으세요. 입장 시작은 원칙적으로 경기 2시간 전입니다.</span></li><li><b>입장 후</b><span>좌석과 가까운 화장실·편의시설을 확인하고 현장의 안전 안내를 따라 주세요.</span></li></ol></div><div className="source-row"><a href="https://tigers.co.kr/tigers/champions-field/team-guide" target="_blank" rel="noreferrer">출처: 구단 구장 안내 · 공식 시설 안내도</a><span>시설 정보 확인: 2026.09.05</span></div></TabsContent>
 <TabsContent value="transport"><div className="guide-heading"><div><p className="eyebrow red">ALL ROADS LEAD TO CHAMPIONS FIELD</p><h3>챔필로 가는 길.</h3><p>출발지를 고르면 대중교통 경로를 안내해 드립니다.</p></div></div><div className="transport-grid"><div className="route-card"><label className="route-label"><TrainFront size={20}/> 어디에서 출발하시나요?<NativeSelect value={origin} onChange={e=>setOrigin(e.target.value as keyof typeof routes)}>{Object.entries(routes).map(([key,r])=><option key={key} value={key}>{r.name}</option>)}</NativeSelect></label><ol className="route-steps"><li><span>01</span><div><small>출발</small><h4>{route.name}</h4></div></li><li><span><Bus size={18}/></span><div><small>버스 탑승</small><h4>{route.bus}</h4></div></li><li><span>03</span><div><small>하차</small><h4>{route.stop}</h4><p>{route.walk}</p></div></li></ol><p className="notice">{route.alternative}</p><p className="muted small">구단 안내 기준 경로입니다. 배차·노선과 실제 소요 시간은 교통 상황에 따라 달라집니다.</p></div><div className="destination-card"><MapPin size={30}/><p className="eyebrow red">YOUR DESTINATION</p><h4>광주-기아<br/>챔피언스 필드</h4><p>북구 서림로 10</p><button className="outline-button" onClick={copyAddress}><Copy size={16}/> 주소 복사</button><p className="small" role="status">{copied}</p><div className="parking-note"><Car size={20}/><div><h5>자가용 · 주차</h5><p>구단은 주차 공간이 협소해 대중교통 이용을 권장합니다. 차량 이용 시 혼잡을 고려해 여유 있게 도착하고 현장 주차 안내를 따라 주세요.</p></div></div></div></div><a className="source-link" href="https://tigers.co.kr/tigers/champions-field/team-guide" target="_blank" rel="noreferrer">경로 출처: KIA 타이거즈 구장 안내 · 2026.09.05 확인</a></TabsContent>
 </Tabs></div><Dialog open={mapOpen} onOpenChange={setMapOpen}><DialogContent className="tigers-dialog map-dialog"><DialogTitle className="dialog-title">챔피언스 필드 안내도</DialogTitle><DialogDescription>확대 후 가로·세로로 스크롤해 블록과 시설 위치를 확인하세요.</DialogDescription><div className="zoom-controls"><button aria-label="안내도 축소" onClick={()=>setZoom(z=>Math.max(1,z-.5))} disabled={zoom<=1}><Minus/></button><span>{zoom*100}%</span><button aria-label="안내도 확대" onClick={()=>setZoom(z=>Math.min(3,z+.5))} disabled={zoom>=3}><Plus/></button></div><div className="map-viewport"><img src={map} style={{width:zoom*100+'%',maxWidth:'none'}} alt="챔피언스 필드 좌석, 입장 게이트 및 편의시설 배치도"/></div><a className="source-link" href={map} target="_blank" rel="noreferrer">공식 안내도 원본</a></DialogContent></Dialog>
 </section>
}
