'use client';
import {useEffect,useState} from 'react';
import {useUrlState} from './url-state';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {NativeSelect} from '@/components/ui/native-select';
import {ChevronLeft,ChevronRight,RefreshCw,ArrowUpRight,CalendarDays,MapPin,Ticket,Clock} from 'lucide-react';
import {type Game,seatOptions,estimatePrice,stateLabel,ticketWindow,TICKET_URL,POLICY_URL} from '@/lib/game-model';
export type Guide={policyCurrent:boolean;policyUrl:string;fieldUrl:string;unavailable?:boolean};
export function useGuide(){const [guide,setGuide]=useState<Guide|null>(null);useEffect(()=>{const c=new AbortController();fetch('/api/guide',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Guide>}).then(setGuide).catch(()=>{});return()=>c.abort()},[]);return guide;}
const money=(n:number)=>n.toLocaleString('ko-KR')+'원';
const kstDay=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
const prettyDate=(date:string)=>new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short',timeZone:'Asia/Seoul'}).format(new Date(date+'T12:00:00+09:00'));
export function TicketEstimate({game,guide,stale=false}:{game:Game;guide:Guide|null;stale?:boolean}){
 const [seatId,setSeatId]=useState('k9');const [quantity,setQuantity]=useState(2);const day=new Date(game.date+'T12:00:00+09:00').getUTCDay();const [rate,setRate]=useState(day===0||day>=5?'weekend':'weekday');const seat=seatOptions.find(s=>s.id===seatId)!;const total=estimatePrice(seatId,quantity,rate);const window=ticketWindow(game);const trusted=guide?.policyCurrent&&!stale;
 return <div className="ticket-estimate"><div className="subheading"><Ticket size={19}/><h4>나의 직관 플랜</h4><span>잔여 좌석 조회 아님</span></div><div className="estimate-fields"><label>좌석 종류<NativeSelect value={seatId} onChange={e=>{setSeatId(e.target.value);const s=seatOptions.find(s=>s.id===e.target.value)!;setQuantity(s.group===1?2:s.group)}}>{seatOptions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</NativeSelect></label><label>입장권 수량<NativeSelect value={quantity} onChange={e=>setQuantity(Number(e.target.value))}>{Array.from({length:8},(_,i)=>i+1).filter(n=>n%seat.group===0).map(n=><option key={n} value={n}>{n}매{seat.group>1?' · '+n/seat.group+'테이블':''}</option>)}</NativeSelect></label><label>요금 기준<NativeSelect value={rate} onChange={e=>setRate(e.target.value)}><option value="weekday">주중 · 월–목</option><option value="weekend">주말 · 금–일 / 공휴일</option></NativeSelect></label></div><p className="seat-note">{seat.area} · {seat.note}</p><p className="muted small">공휴일은 ‘주말 / 공휴일’을 선택해 주세요. 일반 성인 요금이며 할인·예매 수수료는 제외됩니다.</p><div className="estimate-total"><div><span>입장권 예상 금액</span><small>{trusted?`${money(rate==='weekend'?seat.weekend:seat.weekday)} × ${quantity}매`:'최신 요금 확인 필요'}</small></div><strong>{trusted?money(total):'—'}</strong></div>{!trusted&&<p className="notice">{stale?'저장된 경기 정보입니다. 예매 시간과 금액을 최신 정보로 확정할 수 없습니다.':guide===null?'최신 입장권 정책을 확인하고 있습니다.':'공식 정책이 변경되었거나 연결이 지연되고 있습니다. 예상 금액 표시를 중지했습니다.'}</p>}<div className="reservation-state"><Clock size={16}/><b>{trusted?window.label:'예매 상태 확인 필요'}</b>{window.opens&&<span>일반 예매 {new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}).format(window.opens)} 오픈</span>}</div><a className="action-button" href={TICKET_URL} target="_blank" rel="noreferrer">공식 예매처에서 잔여석 확인 <ArrowUpRight size={18}/></a><p className="muted small">이곳의 선택은 관람 계획용입니다. 좌석 확정·로그인·결제는 티켓링크에서 진행하며 선택 내용은 전송되지 않습니다. 매진 여부는 예매처에서 확인합니다.</p><a className="source-link" href={guide?.policyUrl||POLICY_URL} target="_blank" rel="noreferrer">요금 출처: KIA 2026 입장권 안내 (8월 18일 게시)</a></div>
}
export default function Schedule({compact=false}:{compact?:boolean}){
 const [today,setToday]=useState('');const [query,setQuery,ready]=useUrlState({month:'',filter:'all',view:'calendar'},(k,v)=>k==='month'?/^(20\d{2})-(0[1-9]|1[0-2])$/.test(v):k==='filter'?['all','home','away'].includes(v):['calendar','list'].includes(v),!compact);const {month,filter,view}=query;const setMonth=(month:string)=>setQuery({month});const setFilter=(filter:string)=>setQuery({filter});const setView=(view:string)=>setQuery({view});const [games,setGames]=useState<Game[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [meta,setMeta]=useState<{checkedAt:string;stale:boolean;message?:string}|null>(null);const [retry,setRetry]=useState(0);
 useEffect(()=>{if(!ready)return;const d=kstDay();setToday(d);if(!month)setMonth(d.slice(0,7))},[ready]);
 useEffect(()=>{if(!month)return;const c=new AbortController();setLoading(true);setError('');setGames([]);setMeta(null);fetch('/api/schedule?month='+month,{signal:c.signal}).then(async r=>{const data=await r.json() as {games:Game[];checkedAt:string;stale:boolean;message?:string;error?:string};if(!r.ok)throw new Error(data.error||'일정을 불러오지 못했습니다.');return data}).then(data=>{setGames(data.games);setMeta(data);setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false)}});return()=>c.abort()},[month,retry]);
 const changeMonth=(step:number)=>{const [y,m]=month.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+step,1));setMonth(d.toISOString().slice(0,7))};
 const visible=games.filter(g=>filter==='all'||(filter==='home'?g.isHome:!g.isHome));
 const [year,mon]=month.split('-').map(Number);const days=month?new Date(Date.UTC(year,mon,0)).getUTCDate():0;const offset=month?new Date(Date.UTC(year,mon-1,1)).getUTCDay():0;
 const upcoming=games.find(g=>g.date>=today&&g.state!=='cancelled'&&g.state!=='finished');
 const gameHref=(g:Game)=>'/schedule/'+encodeURIComponent(g.id)+'?from='+encodeURIComponent('/schedule?'+new URLSearchParams({month,filter,view}));
 if(compact)return <section className="schedule section home-next"><div className="section-title"><div><p className="eyebrow red">MAKE IT A GAME DAY</p><h2>NEXT <span>GAME.</span></h2></div><a className="text-link" href="/schedule">전체 경기일정 <ArrowUpRight size={18}/></a></div>{loading?<p role="status">다음 경기를 확인하고 있습니다.</p>:error?<p role="alert">{error} <a href="/schedule">경기일정 확인하기</a></p>:upcoming?<a className="next-game" href={gameHref(upcoming)}><span className="next-label">{prettyDate(upcoming.date)}<small>{upcoming.time} · {upcoming.stadium}</small></span><strong>{upcoming.away}<span>VS</span>{upcoming.home}</strong><span className="next-action">경기 상세 · 직관 플랜 <ArrowUpRight size={20}/></span></a>:<p>이 달의 예정 경기가 없습니다. <a className="text-link" href="/schedule">다른 달 일정 확인</a></p>}{meta?.stale&&<p className="notice">{meta.message}</p>}</section>;
 return <section id="schedule" className="schedule section"><div className="section-title"><div><p className="eyebrow red">MAKE IT A GAME DAY</p><h2>GAME <span>ON.</span></h2><p className="section-subtitle">경기를 고르고, 나만의 직관을 준비하세요.</p></div><span className="data-badge"><i/>{meta?.stale?'저장된 일정':loading?'일정 불러오는 중':'공식 일정 연동'}</span></div>
 {!loading&&upcoming&&<a className="next-game" href={gameHref(upcoming)}><span className="next-label">{upcoming.state==='live'?'NOW PLAYING':'NEXT GAME'}<small>{prettyDate(upcoming.date)} · {upcoming.time}</small></span><strong>{upcoming.away}<span>VS</span>{upcoming.home}</strong><span className="next-place"><MapPin size={16}/>{upcoming.stadium}</span><span className="next-action">경기 상세 / 예매 플랜 <ArrowUpRight size={20}/></span></a>}
 <div className="schedule-controls"><div className="month-picker"><button aria-label="이전 달" disabled={!month||year<=2000&&mon===1} onClick={()=>changeMonth(-1)}><ChevronLeft/></button><h3>{month?`${year}. ${String(mon).padStart(2,'0')}`:'—'}</h3><button aria-label="다음 달" disabled={!month||year>=2099&&mon===12} onClick={()=>changeMonth(1)}><ChevronRight/></button><button className="today-button" onClick={()=>{setMonth(kstDay().slice(0,7));setToday(kstDay())}}>이번 달</button></div><div className="schedule-filters"><Tabs value={filter} onValueChange={v=>setFilter(String(v))}><TabsList className="segment" aria-label="홈 원정 필터"><TabsTrigger value="all">전체</TabsTrigger><TabsTrigger value="home">홈</TabsTrigger><TabsTrigger value="away">원정</TabsTrigger></TabsList></Tabs><Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList className="segment" aria-label="일정 보기 방식"><TabsTrigger value="calendar">달력</TabsTrigger><TabsTrigger value="list">목록</TabsTrigger></TabsList></Tabs><button className="icon-button" aria-label="일정 새로고침" onClick={()=>setRetry(n=>n+1)} disabled={loading}><RefreshCw size={18} className={loading?'spinning':''}/></button></div></div>
 {meta?.stale&&<p className="notice" role="status">{meta.message}</p>}
 {loading?<div className="schedule-empty" role="status"><RefreshCw className="spinning"/><p>공식 경기 일정을 불러오고 있습니다.</p></div>:error?<div className="schedule-empty" role="alert"><p>{error}</p><button className="action-button" onClick={()=>setRetry(n=>n+1)}>다시 불러오기</button></div>:<><p className="schedule-count">{visible.length}경기 <span>홈 {games.filter(g=>g.isHome).length} · 원정 {games.filter(g=>!g.isHome).length}</span><small>모든 시각은 한국 시간</small></p>{visible.length===0?<div className="schedule-empty"><CalendarDays/><p>{games.length?'선택한 조건에 해당하는 경기가 없습니다.':'이 달에 등록된 경기가 없습니다.'}</p><span>일정 미발표 또는 비시즌일 수 있습니다.</span></div>:view==='calendar'?<div className="calendar-scroll"><div className="game-calendar"><div className="weekdays">{'일월화수목금토'.split('').map(d=><span key={d}>{d}</span>)}</div><div className="calendar-days">{Array.from({length:offset},(_,i)=><div className="calendar-day blank" key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');const daily=visible.filter(g=>g.date===date);return <div className={'calendar-day '+(date===today?'is-today':'')} key={date}><span className="day-number">{i+1}{date===today&&<small>오늘</small>}</span>{daily.map((game,i)=><a key={game.id} className={'calendar-game '+(game.isHome?'home-game':'away-game')} href={gameHref(game)} aria-label={prettyDate(game.date)+' '+game.opponent+' '+stateLabel[game.state]+' 상세'}><span className="game-type">{game.isHome?'HOME':'AWAY'}{daily.length>1?' · DH '+(i+1):''}</span><strong>{game.opponent}</strong><span>{game.time} · {game.stadium}</span><b className={'result '+game.state}>{game.state==='finished'||game.state==='live'?`${game.awayScore??'—'} : ${game.homeScore??'—'} · ${game.state==='live'?'경기 중':game.result}`:stateLabel[game.state]}</b></a>)}{daily.length===0&&<span className="off-day">—</span>}</div>})}</div></div></div>:<div className="game-list">{visible.map(game=><a className="game-row" key={game.id} href={gameHref(game)}><span className="row-date">{prettyDate(game.date)}<small>{game.time}</small></span><span className={'home-badge '+(game.isHome?'home':'')}>{game.isHome?'홈':'원정'}</span><strong>{game.away}<span>{['finished','live'].includes(game.state)?`${game.awayScore??'—'} : ${game.homeScore??'—'}`:'VS'}</span>{game.home}</strong><span className="row-place">{game.stadium}</span><span className={'result '+game.state}>{stateLabel[game.state]}</span><ChevronRight size={18}/></a>)}</div>}</>}
 <div className="source-row"><a href="https://tigers.co.kr/game/schedule" target="_blank" rel="noreferrer">데이터 출처 · KIA 타이거즈</a><span>{meta&&new Intl.DateTimeFormat('ko-KR',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(meta.checkedAt))+' 확인'}</span></div><p className="muted small">일정·점수는 구단 제공 정보이며 우천 등으로 변경될 수 있습니다. 경기 중 표시는 실시간 중계가 아닙니다. 날짜를 누르면 상세 정보를 볼 수 있습니다.</p>

 </section>
}
